### ISSUE TITLE
Info rest apimu?

### ISSUE THREAD

**Issue by ERLANRAHMAT** [cakrayp/whatsapp-cakrabot-md#2]
Info rest apimu ga di run lagi kah ?

**Comment by cakrayp** [comment]
> Info rest apimu ga di run lagi kah ?

Ohh nanti aja iya ka, karena hosting heroku sudah lagi berbayar, jadi tidak free lagi 😁. Sekarang Mimin lagi perbaikan dan membuat program baru

**Comment by ERLANRAHMAT** [comment]
Baiklah nanti kabarin lagi cuy

**Comment by cakrayp** [comment]
> Baiklah nanti kabarin lagi cuy

Halo kk, ini sudah di rilis api terbaru iya silahkan mampir kk https://cloudsmart.my.id
